if (window.gameInstance && window.gameInstance.player) {
    const player = window.gameInstance.player;
    const critChance = (player.statSystem && player.statSystem.getStatValue('criticalChance')) ?? ...
    const baseDamage = (player.statSystem && player.statSystem.getStatValue('damage')) || ...

